package pt.isec.pa.chess.model;

import pt.isec.pa.chess.model.data.Enumerations.EChessState;
import pt.isec.pa.chess.model.data.Enumerations.EPieceType;
import pt.isec.pa.chess.model.data.Enumerations.ETeamColor;
import pt.isec.pa.chess.model.data.Pieces.GameBoard;
import pt.isec.pa.chess.model.data.Pieces.Piece;
import pt.isec.pa.chess.model.data.game.*;
import pt.isec.pa.chess.model.memento.CareTaker;
import pt.isec.pa.chess.model.memento.IMemento;

import java.beans.PropertyChangeSupport;
import java.beans.PropertyChangeListener;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Manages the overall chess game logic and state, acting as a Facade.
 * <p>
 * This class provides a simplified interface to the chess game's core functionalities.
 * It handles game initialization, piece movements, pawn promotion, game state queries (like check or game over),
 * saving/loading games using serialization, importing/exporting games in text format,
 * and managing undo/redo operations through the Memento pattern.
 * It also uses PropertyChangeSupport to notify observers (typically UI components)
 * of changes in the game state, such as board updates, turn changes, or game events.
 * This class implements IOriginator to serve as the source for creating mementos.
 * All game logic is delegated to the ChessGame class, and logging is handled by
 * the ModelLog singleton.
 *
 * @author Davi Nasser, Miguel Lopes e Ruben Seco
 * @version 1.0.0
 */
public class ChessGameManager {
    public static final String PROP_UNDO_PERFORMED        = "undoPerformed";
    public static final String PROP_REDO_PERFORMED        = "redoPerformed";
    public static final String PROP_LEARNING_MODE_CHANGED = "learningMode";
    public static final String PROP_BOARD_CHANGED         = "boardChanged";
    public static final String PROP_TURN_CHANGED          = "turnChanged";
    public static final String PROP_GAME_STARTED          = "gameStarted";
    public static final String PROP_CHECKMATE             = "checkMate";
    public static final String PROP_GAME_OVER             = "gameOver";
    public static final String PROP_EDIT_MODE             = "editMode";
    public static final String PROP_CHECK                 = "check";

    private transient final PropertyChangeSupport pcs = new PropertyChangeSupport(this);
    private ChessGame game;
    private CareTaker caretaker;

    /**
     * Default constructor for ChessGameManager.
     * <p>
     * Initializes a new ChessGame instance and a CareTaker
     * for managing game states for undo/redo functionality.
     */
    public ChessGameManager() {
        this.game = new ChessGame();
        this.caretaker = new CareTaker(this.game);
    }

    /**
     * Adds a PropertyChangeListener to this manager.
     * <p>
     * The listener will be notified of property changes related to the game state,
     * such as board updates, turn changes, etc.
     *
     * @param property The name of the property to listen on.
     * @param listener The PropertyChangeListener to be added.
     */
    public void addPropertyChangeListener(String property, PropertyChangeListener listener) {
        pcs.addPropertyChangeListener(property, listener);
    }

    /**
     * Adds a PropertyChangeListener to the ModelLog singleton.
     * <p>
     * This allows external components to listen for log updates generated by the model.
     *
     * @param propertyName The name of the log property to listen on (e.g., "logAdded", "logsCleared").
     * @param listener The PropertyChangeListener to be added.
     */
    public void addLogPropertyChangeListener(String propertyName, PropertyChangeListener listener) {
        ModelLog.getInstance().addPropertyChangeListener(propertyName, listener);
    }

    /**
     * Clears all logs from the ModelLog singleton.
     * <p>
     * This action will also trigger a property change event from the ModelLog.
     */
    public void clearLogs() {
        ModelLog.getInstance().clearLogs();
    }

    /**
     * Attempts to move a piece from a source position to a destination position.
     * <p>
     * The current game state is retained only when the move is accepted, so invalid moves do not
     * create undo entries. If the move is successful (validated by the ChessGame model),
     * it fires appropriate property changes (PROP_BOARD_CHANGED, PROP_TURN_CHANGED).
     * If the move results in a check or checkmate, corresponding events (PROP_CHECK, PROP_GAME_OVER)
     * are also fired. The move is logged via ModelLog.
     *
     * @param sourceColumn The 0-indexed column of the piece to move.
     * @param sourceRow The 0-indexed row of the piece to move.
     * @param destColumn The 0-indexed column of the destination position.
     * @param destRow The 0-indexed row of the destination position.
     * @return true if the piece was moved successfully, false otherwise (e.g., invalid move, puts king in check).
     */
    public boolean movePiece(int sourceColumn, int sourceRow, int destColumn, int destRow){
        IMemento beforeMove = game.save();
        boolean moved = game.movePiece(sourceColumn, sourceRow, destColumn, destRow);
        if (moved) {
            caretaker.save(beforeMove);
            pcs.firePropertyChange(PROP_BOARD_CHANGED, null, game.getBoard());
            pcs.firePropertyChange(PROP_TURN_CHANGED, null, game.getCurrentPlayer());

            ModelLog.getInstance().addLog("Movimento de " + (char)('a' + sourceColumn) + (sourceRow + 1) +
                    " para " + (char)('a' + destColumn) + (destRow + 1));

            if (game.gameOver()) {
                pcs.firePropertyChange(PROP_GAME_OVER, null, game.getWinner());
                String winner = getWinner().orElse("Empate");
                ModelLog.getInstance().addLog("Fim de jogo. Vencedor: " + winner);
            }
            if (game.isCheck()) {
                pcs.firePropertyChange(PROP_CHECK, null, game.getCurrentPlayer().team() == ETeamColor.WHITE_TEAM);
                pcs.firePropertyChange(PROP_TURN_CHANGED, null, game.getCurrentPlayer());
            }
        }
        return moved;
    }

    /**
     * Validates if a pawn promotion is currently pending.
     * <p>
     * Delegates to ChessGame.validatePawnPromotion().
     *
     * @return An array [column, row] (0-indexed) of the pawn eligible for promotion,
     * or null if no pawn promotion is pending.
     */
    public int[] validatePawnPromotion(){
        PositionData pd = game.validatePawnPromotion();
        return (pd == null) ? null : new int[]{ pd.col(), pd.row() };
    }

    /**
     * Promotes a pawn at the specified position to a new piece type.
     * <p>
     * Delegates to ChessGame.promotePawn(Position, EPieceType).
     * After promotion, fires a PROP_BOARD_CHANGED event and logs the action.
     * This is one of the special chess moves.
     *
     * @param col The 0-indexed column of the pawn to promote.
     * @param row The 0-indexed row of the pawn to promote.
     * @param newType The EPieceType the pawn will be promoted to (e.g., QUEEN, ROOK).
     */
    public void promotePawn(int col, int row, EPieceType newType){
        Position pos = new Position(col, row);
        game.promotePawn(pos, newType);
        pcs.firePropertyChange(PROP_BOARD_CHANGED, null, game.getBoard());
        ModelLog.getInstance().addLog("Peão promovido para " + newType + " em " +
                (char)('a' + pos.getCol()) + (pos.getRow() + 1));
    }

    /**
     * Checks if a move is available from the specified position when no piece is currently selected.
     * <p>
     * This is used to determine if selecting a piece at the given coordinates is a valid first step of a move.
     * Delegates to ChessGame.availableMoveWithoutSelecedPiece(int, int).
     *
     * @param col The 0-indexed column of the position to check.
     * @param row The 0-indexed row of the position to check.
     * @return {@code true} if a piece at this position can be selected (i.e., it's the current player's piece),
     * {@code false} otherwise.
     */
    public boolean availableMoveWithoutSelecedPiece(int col, int row) {
        return game.availableMoveWithoutSelecedPiece(col, row);
    }

    /**
     * Checks if a move to the specified position is available when a piece is already selected.
     * <p>
     * This is used to validate if the currently selected piece can legally move to the target coordinates.
     * Delegates to ChessGame.availableMoveWithSelectedPiece(int, int).
     *
     * @param col The 0-indexed column of the target position.
     * @param row The 0-indexed row of the target position.
     * @return true if the selected piece can move to this position (e.g., it's an empty square or an opponent's piece),
     * false otherwise (e.g., it's a square occupied by a friendly piece).
     */
    public boolean availableMoveWithSelectedPiece(int col, int row){
        return game.availableMoveWithSelectedPiece(col, row);
    }

    /**
     * Checks if it is currently white's turn.
     * <p>
     * Delegates to ChessGame.getCurrentPlayer().
     *
     * @return true if the current player's team is ETeamColor.WHITE_TEAM, false otherwise.
     */
    public boolean isWhiteTurn(){
        return game.getCurrentPlayer().team() == ETeamColor.WHITE_TEAM;
    }

    /**
     * Checks if the current player's team is ETeamColor.EMPTY.
     * <p>
     * This might indicate a game state where no specific player has a turn,
     * possibly before the game starts or after it has ended.
     * Delegates to ChessGame.getCurrentPlayer().
     *
     * @return true if the current player's team is ETeamColor.EMPTY, false otherwise.
     */
    public boolean isEmptyTurn(){
        return game.getCurrentPlayer().team() == ETeamColor.EMPTY;
    }

    /**
     * Checks if the game has been started.
     * <p>
     * Delegates to ChessGame.getState().
     *
     * @return true if the game state is not null (implying the game has started), false otherwise.
     */
    public boolean isStarted() {
        return game.getState() != null;
    }

    /**
     * Checks if the current player is in check.
     * <p>
     * Delegates to ChessGame.isCheck().
     *
     * @return true if the current player's king is in check, false otherwise.
     */
    public boolean isCheck() {
        return game.isCheck();
    }

    /**
     * Validates if a move from a given source position to a destination position is a valid move for the piece at the source.
     * <p>
     * This involves checking the piece's specific movement rules and ensuring the move doesn't leave the king in check.
     * Delegates to ChessGame.getValidMoves(Position).
     *
     * @param fromCol The 0-indexed column of the source position.
     * @param fromRow The 0-indexed row of the source position.
     * @param toCol The 0-indexed column of the destination position.
     * @param toRow The 0-indexed row of the destination position.
     * @return true if the move is valid according to game rules, false otherwise.
     */
    public boolean isMoveValid(int fromCol, int fromRow, int toCol, int toRow) {
        Position from = new Position(fromCol, fromRow);
        Position to   = new Position(toCol,   toRow);

        List<Position> list = game.getValidMoves(from);

        return list.contains(to);
    }

    /**
     * Checks if there is a piece at the specified board coordinates.
     * <p>
     * Delegates to 'GameBoard.getPiece(int, int)' via 'ChessGame.getBoard()'.
     *
     * @param col The 0-indexed column of the position.
     * @param row The 0-indexed row of the position.
     * @return true if there is a piece at the specified coordinates, false otherwise or if coordinates are invalid.
     */
    public boolean hasPiece(int col, int row) {
        return game.getBoard().getPiece(col, row) != null;
    }

    /**
     * Starts a new chess game with the specified player names.
     * <p>
     * Initializes a new game in ChessGame, resets the CareTaker for undo/redo history,
     * saves the initial state, and fires property changes (PROP_GAME_STARTED,
     * PROP_BOARD_CHANGED, PROP_TURN_CHANGED) to update observers.
     * Logs the new game event.
     *
     * @param nameWhite The name of the player controlling the white pieces.
     * @param nameBlack The name of the player controlling the black pieces.
     */
    public void newGame(String nameWhite, String nameBlack) {
        game.newGame(nameWhite, nameBlack);
        caretaker.reset();
        pcs.firePropertyChange(PROP_GAME_STARTED, null, null);
        pcs.firePropertyChange(PROP_BOARD_CHANGED, null, game.getBoard());
        pcs.firePropertyChange(PROP_TURN_CHANGED, null, game.getCurrentPlayer());
        ModelLog.getInstance().addLog("Novo jogo iniciado entre " + nameWhite + " e " + nameBlack);
    }

    /**
     * Loads a chess game from a specified file using object serialization.
     * <p>
     * Uses ChessGameSerialization.loadGame(String) to deserialize the game state.
     * If successful, updates the current game, resets the CareTaker,
     * and fires property changes (PROP_GAME_STARTED, PROP_BOARD_CHANGED,
     * PROP_TURN_CHANGED). Logs the load game event.
     *
     * @param source The File from which to load the game. The file should contain a serialized ChessGame object.
     * @return true if the game was loaded successfully, false otherwise.
     * @throws IOException If an I/O error occurs during deserialization.
     * @throws ClassNotFoundException If the class of a serialized object cannot be found.
     */
    public boolean loadGame(File source) throws IOException, ClassNotFoundException {
        ChessGame loaded = ChessGameSerialization.loadGame(source.getAbsolutePath());
        if (loaded == null) return false;

        this.game = loaded;
        this.caretaker = new CareTaker(this.game);
        pcs.firePropertyChange(PROP_GAME_STARTED, null, null);
        pcs.firePropertyChange(PROP_BOARD_CHANGED, null, game.getBoard());
        pcs.firePropertyChange(PROP_TURN_CHANGED, null, game.getCurrentPlayer());
        ModelLog.getInstance().addLog("Jogo carregado com sucesso de: " + source.getAbsolutePath());
        return true;
    }

    /**
     * Saves the current chess game to a specified file using object serialization.
     * <p>
     * Uses ChessGameSerialization.saveGame(ChessGame, String) to serialize the current game state.
     * Logs the save game event.
     *
     * @param destiny The File to which the game will be saved.
     * @throws IOException If an I/O error occurs during serialization.
     */
    public void saveGame(File destiny) throws IOException {
        ChessGameSerialization.saveGame(game, destiny.getAbsolutePath());
        ModelLog.getInstance().addLog("Jogo guardado em: " + destiny.getAbsolutePath());
    }

    /**
     * Imports a game state from a specified text file.
     * <p>
     * Delegates to ChessGame.importGameState(File). The file should be in the
     * format: "CURRENT_TEAM,Piece1Text,Piece2Text,...".
     * If successful, updates the current game, resets the CareTaker,
     * and fires property changes (PROP_GAME_STARTED, PROP_BOARD_CHANGED,
     * PROP_TURN_CHANGED). Logs the import event.
     * Player names for an imported game must be set separately using setImportGameData(String, String).
     *
     * @param source The File from which to import the game state.
     * @return true if the game was imported successfully, false otherwise.
     */
    public boolean importGame(File source){
        boolean result = game.importGameState(source);
        if (result) {
            caretaker.reset();
            pcs.firePropertyChange(PROP_GAME_STARTED, null, null);
            pcs.firePropertyChange(PROP_BOARD_CHANGED, null, game.getBoard());
            pcs.firePropertyChange(PROP_TURN_CHANGED, null, game.getCurrentPlayer());

            ModelLog.getInstance().addLog("Jogo importado de: " + source.getAbsolutePath());
        }
        return result;
    }

    /**
     * Exports the current game state to a specified text file.
     * <p>
     * Delegates to ChessGame.exportGameState(File). The game is exported in the
     * format: "CURRENT_TEAM,Piece1Text,Piece2Text,...".
     * Logs the export event.
     *
     * @param destiny The File to which the game state will be exported.
     * @return true if the game was exported successfully, false otherwise.
     */
    public boolean exportGame(File destiny){
        ModelLog.getInstance().addLog("Jogo exportado para: " + destiny.getAbsolutePath());
        return game.exportGameState(destiny);
    }

    /**
     * Sets the player names for an imported game.
     * <p>
     * This method is typically called after importGame(File) if the imported
     * format does not include player names, or to allow users to define them.
     * Delegates to ChessGame.setImportGameData(String, String).
     *
     * @param whitePlayerName The name for the white player.
     * @param blackPlayerName The name for the black player.
     */
    public void setImportGameData(String whitePlayerName, String blackPlayerName) {
        game.setImportGameData(whitePlayerName, blackPlayerName);
    }

    /**
     * Changes the state of the learning mode.
     * <p>
     * Fires a PROP_LEARNING_MODE_CHANGED property change event to notify listeners
     * about the change in the learning mode status.
     *
     * @param learningModeActive true to activate learning mode, false to deactivate it.
     */
    public void changeLearningMode(boolean learningModeActive){
        pcs.firePropertyChange(PROP_LEARNING_MODE_CHANGED, null, learningModeActive);
    }

    /**
     * Quits the current game.
     * <p>
     * This method signals the underlying ChessGame to end and fires a PROP_GAME_OVER
     * property change event.
     */
    public void quitGame(){
        game.quitGame();
        pcs.firePropertyChange(PROP_GAME_OVER, null, null);
    }

    /**
     * Undoes the last action by restoring the previous game state from the CareTaker.
     * <p>
     * The CareTaker will call restore on the ChessGame instance (the Originator).
     * After the state is restored in ChessGame, this manager fires relevant property changes
     * to update the UI with the restored state, and a PROP_UNDO_PERFORMED event.
     */
    public void undo() {
        if (caretaker.hasUndo()) {
            caretaker.undo();
            pcs.firePropertyChange(PROP_BOARD_CHANGED, null, game.getBoard());
            pcs.firePropertyChange(PROP_TURN_CHANGED, null, game.getCurrentPlayer());
            if (game.gameOver()) {
                pcs.firePropertyChange(PROP_GAME_OVER, null, game.getWinner());
                if (game.getState() == EChessState.CHECKMATE_WHITE_WON || game.getState() == EChessState.CHECKMATE_BLACK_WON) {
                    pcs.firePropertyChange(PROP_CHECKMATE, null, game.getWinner());
                }
            } else if (game.isCheck()) {
                pcs.firePropertyChange(PROP_CHECK, null, game.getCurrentPlayer().team() == ETeamColor.WHITE_TEAM);
            }
            pcs.firePropertyChange(PROP_UNDO_PERFORMED, null, null);
            ModelLog.getInstance().addLog("Undo realizado");
        }
    }

    /**
     * Redoes the last undone action by restoring a future game state from the CareTaker.
     * <p>
     * The CareTaker will call restore on the ChessGame instance (the Originator).
     * After the state is restored in ChessGame, this manager fires relevant property changes
     * to update the UI with the restored state, and a PROP_REDO_PERFORMED event.
     */
    public void redo() {
        if (caretaker.hasRedo()) {
            caretaker.redo();
            pcs.firePropertyChange(PROP_BOARD_CHANGED, null, game.getBoard());
            pcs.firePropertyChange(PROP_TURN_CHANGED, null, game.getCurrentPlayer());
            if (game.gameOver()) {
                pcs.firePropertyChange(PROP_GAME_OVER, null, game.getWinner());
                if (game.getState() == EChessState.CHECKMATE_WHITE_WON || game.getState() == EChessState.CHECKMATE_BLACK_WON) {
                    pcs.firePropertyChange(PROP_CHECKMATE, null, game.getWinner());
                }
            } else if (game.isCheck()) {
                pcs.firePropertyChange(PROP_CHECK, null, game.getCurrentPlayer().team() == ETeamColor.WHITE_TEAM);
            }
            pcs.firePropertyChange(PROP_REDO_PERFORMED, null, null);
            ModelLog.getInstance().addLog("Redo realizado");
        }
    }

    /**
     * Starts the board edit mode.
     * <p>
     * This mode allows users to freely place or remove pieces on the board.
     * It initializes the game for editing and fires property changes for game start,
     * board update, turn change (potentially to a neutral state), and edit mode activation.
     */
    public void startEditMode() {
        game.startEditMode();
        pcs.firePropertyChange(PROP_GAME_STARTED, null, null);
        pcs.firePropertyChange(PROP_BOARD_CHANGED, null, game.getBoard());
        pcs.firePropertyChange(PROP_TURN_CHANGED, null, game.getCurrentPlayer());
        pcs.firePropertyChange(PROP_EDIT_MODE, null, true);
    }

    /**
     * Adds a piece of a specified type and color to the board at the given coordinates,
     * typically used in edit mode.
     * <p>
     * Delegates the action to the ChessGame instance. If the piece is successfully added,
     * a PROP_BOARD_CHANGED event is fired.
     *
     * @param type The EPieceType of the piece to add.
     * @param isWhite true if the piece is white, false if it is black.
     * @param col The 0-indexed column where the piece will be placed.
     * @param row The 0-indexed row where the piece will be placed.
     * @return true if the piece was successfully added, false otherwise (e.g., position occupied, invalid position).
     */
    public boolean addPiece(EPieceType type, boolean isWhite, int col, int row){
        boolean result = game.addPiece(type, isWhite, col, row);
        if(result)
            pcs.firePropertyChange(PROP_BOARD_CHANGED, null, game.getBoard());
        return result;
    }

    /**
     * Removes a piece from the board at the given coordinates, typically used in edit mode.
     * <p>
     * Delegates the action to the ChessGame instance. If a piece is successfully removed,
     * a PROP_BOARD_CHANGED event is fired.
     *
     * @param col The 0-indexed column of the piece to remove.
     * @param row The 0-indexed row of the piece to remove.
     * @return true if a piece was successfully removed, false otherwise (e.g., no piece at the position).
     */
    public boolean removePiece(int col, int row){
        boolean result = game.removePiece(col, row);
        if(result)
            pcs.firePropertyChange(PROP_BOARD_CHANGED, null, game.getBoard());
        return result;
    }

    /**
     * Configures the edited game state before saving or exporting.
     * <p>
     * Sets the names of the white and black players and determines which side moves first
     * in the edited configuration. This method should be called when the user confirms
     * they want to save or export an edited board layout.
     *
     * @param whiteName       Name of the player controlling the white pieces.
     * @param blackName       Name of the player controlling the black pieces.
     * @param isWhiteTeamTurn true if the white side should move first; false if the black side should move first.
     */
    public void configureEditedGameForSave(String whiteName, String blackName, boolean isWhiteTeamTurn) {
        game.configureEditedGameForSave(whiteName, blackName, isWhiteTeamTurn);
    }

    /**
     * Ends the board edit mode without saving the changes made.
     * <p>
     * The game state should revert to what it was before entering edit mode,
     * or to a default state if no prior state is defined.
     * Fires property changes to reflect that the game is "over" (in terms of editing)
     * and that edit mode is deactivated.
     */
    public void endEditMode(){
        game.endEditModeWithoutSave();
        pcs.firePropertyChange(PROP_GAME_OVER, null, null);
        pcs.firePropertyChange(PROP_EDIT_MODE, null, false);
    }

    /**
     * Gets the current state of the chess game.
     * <p>
     * Delegates to ChessGame.getState().
     *
     * @return The current EChessState of the game (e.g., IN_PROGRESS, CHECK, CHECKMATE_WHITE_WON).
     */
    public EChessState getState() {
        return game.getState();
    }

    /**
     * Gets the name of the player for the specified team color.
     * <p>
     * Delegates to ChessGame.getPlayerName(boolean).
     *
     * @param isWhiteTeam true to get the white player's name,
     * false to get the black player's name.
     * @return The name of the player as a String.
     */
    public String getPlayerName(boolean isWhiteTeam) {
        return game.getPlayerName(isWhiteTeam);
    }

    /**
     * Gets a clone of the current game board.
     * <p>
     * Delegates to ChessGame.getBoard(), which should return a defensive copy
     * to prevent external modification of the internal game state.
     *
     * @return A GameBoard object representing the current state of the chess board.
     */
    public GameBoard getBoard() {
        return game.getBoard();
    }

    /**
     * Gets the type of the piece at the specified board coordinates.
     * <p>
     * Delegates to ChessGame.getPieceAt(Position).
     *
     * @param col The 0-indexed column of the position.
     * @param row The 0-indexed row of the position.
     * @return The EPieceType of the piece at the given coordinates (e.g., PAWN, ROOK),
     * or null if the square is empty or the coordinates are invalid.
     */
    public EPieceType getPieceTypeAt(int col, int row) {
        Piece piece = game.getPieceAt(new Position(col, row));
        return piece != null ? piece.getEPieceType() : null;
    }

    /**
     * Gets a list of valid moves for the piece at the specified board coordinates.
     * <p>
     * Each move is represented as an integer array 'destinationColumn, destinationRow'.
     * Delegates to ChessGame.getValidMoves(Position).
     *
     * @param col The 0-indexed column of the piece.
     * @param row The 0-indexed row of the piece.
     * @return A List of int[] representing valid destination coordinates.
     * Returns an empty list if there is no piece at the location or no valid moves.
     */
    public List<int[]> getValidMoves(int col, int row) {
        List<Position> list = game.getValidMoves(new Position(col, row));

        List<int[]> moves = new ArrayList<>(list.size());
        for (Position p : list)
            moves.add(new int[]{ p.getCol(), p.getRow() });
        return moves;
    }

    /**
     * Gets the name of the winner if the game is over and has a winner.
     * <p>
     * Delegates to ChessGame.getWinner().
     *
     * @return An Optional containing the name of the winning player as a String.
     * Returns an empty Optional if the game is a draw or not yet over.
     */
    public Optional<String> getWinner() {
        PlayerData winner = game.getWinner();
        return winner != null ? Optional.of(winner.name()) : Optional.empty();
    }

    /**
     * Returns whether the game is currently in edit mode.
     * <p>
     * Delegates to ChessGame.isEditModeActive().
     *
     * @return true if edit mode is active; false otherwise.
     */
    public boolean isEditModeActive() {
        return game.isEditModeActive();
    }

    /**
     * Activates or deactivates edit mode for the current game.
     * <p>
     * When edit mode is active, pieces can be freely added or removed on the board.
     *
     * @param editModeActive true to enter edit mode; false to exit edit mode.
     */
    public void setEditModeActive(boolean editModeActive) {
        game.setEditModeActive(editModeActive);
    }
}


