package pt.isec.pa.chess.model.data.game;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.ArrayList;
import java.util.List;

/**
 * Manages a collection of log entries for the chess game model, implemented as a Singleton.
 * <p>
 * This class provides a centralized way to record significant events or messages
 * generated by the game model. It allows adding new log entries and clearing all existing logs.
 * It also supports observability through PropertyChangeSupport, firing events
 * when logs are added or cleared, allowing other components (like a UI log window)
 * to react to these changes.
 *
 * @author Davi Nasser, Miguel Lopes e Ruben Seco
 * @version 1.0.0
 */
public class ModelLog {
    private static ModelLog instance;

    private final List<String> logs;
    private final PropertyChangeSupport pcs;

    /**
     * Private constructor to prevent instantiation from outside and enforce the Singleton pattern.
     * <p>
     * Initializes an empty list for logs and a PropertyChangeSupport object for managing listeners.
     */
    private ModelLog() {
        logs = new ArrayList<>();
        pcs = new PropertyChangeSupport(this);
    }

    /**
     * Returns the single instance of the ModelLog class.
     * <p>
     * If an instance does not already exist, it is created in a thread-safe manner.
     * This method ensures that only one ModelLog object is used throughout the application.
     *
     * @return The singleton ModelLog instance.
     */
    public static synchronized ModelLog getInstance() {
        if (instance == null)
            instance = new ModelLog();
        return instance;
    }

    /**
     * Adds a new log entry to the collection.
     * <p>
     * After adding the entry, this method fires a property change event with the
     * property name "logAdded", the old value as null, and the new value as the added entry string.
     *
     * @param entry The string message to be added as a log entry.
     */
    public void addLog(String entry) {
        logs.add(entry);
        pcs.firePropertyChange("logAdded", null, entry);
    }

    /**
     * Clears all existing log entries from the collection.
     * <p>
     * After clearing the logs, this method fires a property change event with the
     * property name "logsCleared", and both old and new values as null.
     */
    public void clearLogs() {
        logs.clear();
        pcs.firePropertyChange("logsCleared", null, null);
    }

    /**
     * Adds a PropertyChangeListener to listen for log-related events.
     * <p>
     * Listeners can subscribe to specific property names like "logAdded" or "logsCleared"
     * to be notified when these events occur.
     *
     * @param propertyName The name of the property to listen on.
     * @param listener The PropertyChangeListener to be added.
     */
    public void addPropertyChangeListener(String propertyName, PropertyChangeListener listener) {
        pcs.addPropertyChangeListener(propertyName, listener);
    }
}
